### ISSUE TITLE
state: absent dictionary option

### ISSUE THREAD

**Issue by mabed-fr** [robertdebock/ansible-role-logrotate#20]
Hello,

Great role.

Is it possible to add the "state: absent" key like this:

```
logrotate_entries:
  - name: haproxy
    state: absent ### That 
    path: "/var/log/haproxy.log"
    compress: true
    copytruncate: true
    delaycompress: false
    missingok: true
    notifempty: true
    dateext: true
    dateformat: "-%d-%m-%Y"
```

This could trigger the deletion of logrotate deployer files with the role

What do you think?
