### ISSUE TITLE
"create" cannot be configured in logrotate.conf

### ISSUE THREAD

**Issue by jqiuyin** [robertdebock/ansible-role-logrotate#26]
# Describe the bug

"create" in logrotate.conf is fixed
https://github.com/robertdebock/ansible-role-logrotate/blob/cda13016882f54740f72c92648574c126b199138/templates/logrotate.conf.j2#L15
set `create: false` in entry conf will not change the global config  
```
logrotate_entries:
  - name: remote-linux-syslog
    path: "/var/log/linux_syslog/*/message"
    frequency: weekly
    compress: true
    create: false
    keep: 48
    dateext: yes
    missingok: true
    sharedscripts: true
    postrotate: "/bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true"
```
if one log file is empty, logrotate will pack an empty file again and again  
like this:
![image](https://github.com/user-attachments/assets/6c1ed3eb-4267-4fe9-9b50-19e3754abe09)
